stages:
- build

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH

build:
  only:
    refs:
      - master
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --tag $CONTAINER_IMAGE:$CI_JOB_ID --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_JOB_ID
    - docker push $CONTAINER_IMAGE:latest
